"""Render a resolved scene into Hyprland Lua.

Field choices follow IM0001GT/omarchy-screens' monitor_lua (MIT, (c) 2026
IM0001GT): HDR "auto" only marks the output HDR-capable and lets
render.cm_auto_hdr flip to HDR for fullscreen HDR content, so the desktop is
not washed out; "always" pins an HDR colour-management preset.
"""

from __future__ import annotations

from dataclasses import dataclass

from .hypr import lua_str


@dataclass
class ResolvedMonitor:
    connector: str
    mode: str
    position: str = "auto"
    scale: float = 1.0
    transform: int = 0
    vrr: int = 0
    hdr: str = "off"
    bpc: int = 8
    sdr_brightness: float = 1.0
    wide_gamut: bool = False
    max_luminance: int | None = None
    max_avg_luminance: int | None = None


def _num(n: float) -> str:
    text = ("%.4f" % float(n)).rstrip("0").rstrip(".")
    return text or "0"


def monitor_line(m: ResolvedMonitor) -> str:
    fields = [
        f"output = {lua_str(m.connector)}",
        f"mode = {lua_str(m.mode)}",
        f"position = {lua_str(m.position)}",
        f"scale = {_num(m.scale)}",
    ]
    if m.transform:
        fields.append(f"transform = {m.transform}")
    fields.append(f"vrr = {int(m.vrr)}")
    if m.hdr in ("auto", "always"):
        fields.append(f"bitdepth = {10 if m.bpc >= 10 else 8}")
        fields.append("supports_hdr = 1")
    if m.hdr == "always":
        fields.append(f"cm = {lua_str('hdr' if m.wide_gamut else 'hdredid')}")
        fields.append("sdr_min_luminance = 0.005")
        peak = m.max_avg_luminance or m.max_luminance or 203
        fields.append(f"sdr_max_luminance = {max(80, min(int(peak), 1000))}")
        fields.append(f"sdrbrightness = {_num(m.sdr_brightness)}")
        if m.wide_gamut:
            fields.append("supports_wide_color = 1")
    return "hl.monitor({ " + ", ".join(fields) + " })"


def auto_hdr_render(monitors: list[ResolvedMonitor]) -> int:
    autos = [m for m in monitors if m.hdr == "auto"]
    if not autos:
        return 0
    # 1 switches to the "hdr" preset, 2 to "hdredid"; panels that do not
    # advertise BT.2020 look wrong under the wide preset.
    return 1 if all(m.wide_gamut for m in autos) else 2


def render(scene_name: str, monitors: list[ResolvedMonitor], disabled: list[str]) -> str:
    lines = [
        "-- Generated by Battlestation (io.github.samueljenkinsml.battlestation).",
        f"-- Scene: {scene_name}. Do not edit; switch scenes from the bar or run",
        "-- `battlestation scene apply <name>`. Delete this file to fall back to monitors.lua.",
    ]
    for m in monitors:
        lines.append(monitor_line(m))
    for name in disabled:
        lines.append(f"hl.monitor({{ output = {lua_str(name)}, disabled = true }})")
    max_vrr = max((m.vrr for m in monitors), default=0)
    lines.append(
        "hl.config({ misc = { vrr = %d }, render = { cm_auto_hdr = %d } })"
        % (max_vrr, auto_hdr_render(monitors))
    )
    return "\n".join(lines) + "\n"
