"""Render a resolved scene into Hyprland Lua.

Field choices follow IM0001GT/omarchy-screens' monitor_lua (MIT, (c) 2026
IM0001GT): HDR "auto" only marks the output HDR-capable and lets
render.cm_auto_hdr flip to HDR for fullscreen HDR content, so the desktop is
not washed out; "always" pins an HDR colour-management preset.
"""

from __future__ import annotations

from dataclasses import dataclass

from .hypr import lua_str


@dataclass
class ResolvedMonitor:
    connector: str
    mode: str
    position: str = "auto"
    scale: float = 1.0
    transform: int = 0
    vrr: int = 0
    hdr: str = "off"
    bpc: int = 8
    sdr_brightness: float = 1.0
    wide_gamut: bool = False
    max_luminance: int | None = None
    max_avg_luminance: int | None = None


def _num(n: float) -> str:
    text = ("%.4f" % float(n)).rstrip("0").rstrip(".")
    return text or "0"


def monitor_line(m: ResolvedMonitor) -> str:
    fields = [
        f"output = {lua_str(m.connector)}",
        f"mode = {lua_str(m.mode)}",
        f"position = {lua_str(m.position)}",
        f"scale = {_num(m.scale)}",
    ]
    if m.transform:
        fields.append(f"transform = {m.transform}")
    fields.append(f"vrr = {int(m.vrr)}")
    if m.hdr in ("auto", "always"):
        fields.append(f"bitdepth = {10 if m.bpc >= 10 else 8}")
        fields.append("supports_hdr = 1")
    if m.hdr == "always":
        fields.append(f"cm = {lua_str('hdr' if m.wide_gamut else 'hdredid')}")
        fields.append("sdr_min_luminance = 0.005")
        peak = m.max_avg_luminance or m.max_luminance or 203
        fields.append(f"sdr_max_luminance = {max(80, min(int(peak), 1000))}")
        fields.append(f"sdrbrightness = {_num(m.sdr_brightness)}")
        if m.wide_gamut:
            fields.append("supports_wide_color = 1")
    return "hl.monitor({ " + ", ".join(fields) + " })"


def auto_hdr_render(monitors: list[ResolvedMonitor]) -> int:
    autos = [m for m in monitors if m.hdr == "auto"]
    if not autos:
        return 0
    # 1 switches to the "hdr" preset, 2 to "hdredid"; panels that do not
    # advertise BT.2020 look wrong under the wide preset.
    return 1 if all(m.wide_gamut for m in autos) else 2


def render(scene_name: str, monitors: list[ResolvedMonitor], disabled: list[str]) -> str:
    lines = [
        "-- Generated by Battlestation (io.github.samueljenkinsml.battlestation).",
        f"-- Scene: {scene_name}. Do not edit; switch scenes from the bar or run",
        "-- `battlestation scene apply <name>`. Delete this file to fall back to monitors.lua.",
    ]
    for m in monitors:
        lines.append(monitor_line(m))
    for name in disabled:
        lines.append(f"hl.monitor({{ output = {lua_str(name)}, disabled = true }})")
    max_vrr = max((m.vrr for m in monitors), default=0)
    lines.append(
        "hl.config({ misc = { vrr = %d }, render = { cm_auto_hdr = %d } })"
        % (max_vrr, auto_hdr_render(monitors))
    )
    return "\n".join(lines) + "\n"


# -- stream overlay ----------------------------------------------------------------
#
# A second file that loads after the scene overlay. Parked, it keeps the
# virtual output lit but out of the way: switched off, a TV dropping off HDMI
# would leave Hyprland with no output at all, and coming back from its
# placeholder output has frozen the display on NVIDIA. XWayland lists the lit
# output too; xwayland.py keeps the real display primary so Wine games open
# there. Attached, it also switches every physical output off so the desktop
# moves onto the virtual one; Hyprland migrates the workspaces by itself in
# both directions.

PARK_POSITION = "20000x0"  # positive (XWayland cannot do negative) and not adjacent, so the pointer cannot wander in
PARK_WORKSPACE = 99


def render_stream(output: str, mode: str, scale: float = 1.0, attached: bool = False,
                  disable: list[str] | None = None, instance: str | None = None) -> str:
    """Parked, or attached: the virtual output at the client's mode and at the
    origin, with every output in `disable` switched off.

    The attached rules only hold for the compositor instance that was running
    at attach. After a reboot or a Hyprland restart the virtual output is gone,
    and without the guard this file would leave every real display switched off.
    """
    lines = [
        "-- Generated by Battlestation (io.github.samueljenkinsml.battlestation).",
        f"-- Stream overlay: {'attached' if attached else 'parked'}. Do not edit; use `battlestation stream on|off`.",
        "-- Safe to delete: the displays fall back to the scene overlay and monitors.lua.",
        "hl.monitor({ output = %s, mode = %s, position = %s, scale = %s })"
        % (lua_str(output), lua_str(mode), lua_str("0x0" if attached else PARK_POSITION), _num(scale)),
        "hl.workspace_rule({ workspace = %s, monitor = %s, default = true })"
        % (lua_str(PARK_WORKSPACE), lua_str(output)),
    ]
    if attached and disable:
        if not instance:
            raise ValueError("an attached stream overlay needs the compositor instance for its guard")
        lines.append(f'if os.getenv("HYPRLAND_INSTANCE_SIGNATURE") == {lua_str(instance)} then')
        for name in disable or []:
            lines.append(f"  hl.monitor({{ output = {lua_str(name)}, disabled = true }})")
        lines.append("  hl.config({ misc = { vrr = 0 }, render = { cm_auto_hdr = 0 } })")
        lines.append("end")
    return "\n".join(lines) + "\n"
