"""MangoHud as the FPS source.

MangoHud's control socket cannot report FPS, so we use its CSV logger: rows
are flushed as they are written, one per log_interval. `no_display` disables
data collection entirely (MangoHud issue #1782), so the HUD stays visible but
minimal.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import sys
import time
from pathlib import Path

from . import fsutil, paths

MARKER = "X-Battlestation-Override=true"

HUD_STYLES = {
    # A single small FPS readout in the corner.
    "minimal": ["fps_only", "position=top-right", "font_size=18", "background_alpha=0.25"],
    # Fully transparent. Unverified across MangoHud versions; use `minimal` if FPS stops updating.
    "hidden": ["fps_only", "position=top-right", "alpha=0.0", "background_alpha=0.0"],
}


def render_config(style: str = "minimal") -> str:
    lines = [
        "# Generated by Battlestation. Edit via `battlestation setup mangohud --style`.",
        *HUD_STYLES.get(style, HUD_STYLES["minimal"]),
        "toggle_hud=Shift_R+F12",
        "autostart_log=1",
        "log_interval=1000",
        "log_duration=0",
        f"output_folder={paths.mangohud_log_dir()}",
    ]
    return "\n".join(lines) + "\n"


def render_desktop_override(system_desktop: str, config_path: Path) -> str:
    env = f"env MANGOHUD=1 MANGOHUD_CONFIGFILE={config_path} "
    out = []
    for line in system_desktop.splitlines():
        if line.startswith("Exec=") and "/usr/bin/steam" in line and "MANGOHUD" not in line:
            line = "Exec=" + env + line[len("Exec="):]
        out.append(line)
        if line.strip() == "[Desktop Entry]":
            out.append(MARKER)
    return "\n".join(out) + "\n"


def installed() -> bool:
    return shutil.which("mangohud") is not None


def install(style: str = "minimal") -> dict:
    fsutil.atomic_write(paths.mangohud_config(), render_config(style))
    paths.mangohud_log_dir().mkdir(parents=True, exist_ok=True)
    override = paths.steam_desktop_override()
    existing = fsutil.read_text(override)
    if existing is not None and MARKER not in existing:
        return {"config": str(paths.mangohud_config()), "desktop": None,
                "warning": f"{override} exists and is not ours; left untouched. "
                           "Add MANGOHUD=1 MANGOHUD_CONFIGFILE=... to its Exec lines yourself."}
    system = fsutil.read_text(Path("/usr/share/applications/steam.desktop"))
    if system is None:
        return {"config": str(paths.mangohud_config()), "desktop": None, "warning": "steam.desktop not found"}
    fsutil.atomic_write(override, render_desktop_override(system, paths.mangohud_config()))
    return {"config": str(paths.mangohud_config()), "desktop": str(override)}


def remove() -> dict:
    override = paths.steam_desktop_override()
    existing = fsutil.read_text(override)
    removed = []
    if existing is not None and MARKER in existing:
        override.unlink()
        removed.append(str(override))
    if paths.mangohud_config().exists():
        paths.mangohud_config().unlink()
        removed.append(str(paths.mangohud_config()))
    return {"removed": removed}


def override_active() -> bool:
    text = fsutil.read_text(paths.steam_desktop_override())
    return bool(text and MARKER in text)


def steam_env() -> dict[str, str]:
    """Environment to launch Steam with so games inherit MangoHud."""
    if not (installed() and paths.mangohud_config().exists()):
        return {}
    return {"MANGOHUD": "1", "MANGOHUD_CONFIGFILE": str(paths.mangohud_config())}


# -- log tailing -----------------------------------------------------------------

_SUMMARY = re.compile(r"_summary\.csv$")


def newest_log(folder: Path, since: float) -> Path | None:
    best = None
    try:
        entries = list(folder.iterdir())
    except OSError:
        return None
    for p in entries:
        if p.suffix != ".csv" or _SUMMARY.search(p.name):
            continue
        try:
            mtime = p.stat().st_mtime
        except OSError:
            continue
        if mtime >= since and (best is None or mtime > best[0]):
            best = (mtime, p)
    return best[1] if best else None


def prune(folder: Path, max_age_s: float = 86400) -> None:
    cutoff = time.time() - max_age_s
    try:
        for p in folder.iterdir():
            if p.suffix == ".csv" and p.stat().st_mtime < cutoff:
                p.unlink()
    except OSError:
        pass


class CsvFollower:
    """Parses MangoHud CSV lines incrementally, finding the fps column header."""

    def __init__(self):
        self.columns: list[str] | None = None
        self._partial = ""

    def feed(self, chunk: str) -> list[dict]:
        rows = []
        data = self._partial + chunk
        lines = data.split("\n")
        self._partial = lines.pop()
        for line in lines:
            line = line.strip()
            if not line:
                continue
            cells = line.split(",")
            if cells[0] == "fps":
                self.columns = cells
                continue
            if self.columns is None or len(cells) < len(self.columns):
                continue
            row = dict(zip(self.columns, cells))
            try:
                rows.append({
                    "fps": round(float(row["fps"]), 1),
                    "frametime": round(float(row.get("frametime") or 0), 2),
                    "gpuLoad": float(row.get("gpu_load") or 0),
                })
            except ValueError:
                continue
        return rows


def tail(poll_s: float = 0.5, stale_s: float = 3.0) -> None:
    """Emit {"fps": ...} JSON lines for the most recent MangoHud log. Runs forever."""
    folder = paths.mangohud_log_dir()
    folder.mkdir(parents=True, exist_ok=True)
    prune(folder)
    started = time.time() - 5
    current: Path | None = None
    fh = None
    follower = CsvFollower()
    last_row = 0.0
    announced_stale = True

    def out(obj):
        sys.stdout.write(json.dumps(obj, separators=(",", ":")) + "\n")
        sys.stdout.flush()

    while True:
        newest = newest_log(folder, started)
        if newest and newest != current:
            if fh:
                fh.close()
            current, fh, follower = newest, open(newest, encoding="utf-8", errors="replace"), CsvFollower()
            out({"event": "log", "file": current.name})
        if fh:
            rows = follower.feed(fh.read())
            if rows:
                last_row = time.time()
                announced_stale = False
                out({"event": "fps", **rows[-1]})
        if not announced_stale and time.time() - last_row > stale_s:
            announced_stale = True
            out({"event": "fps", "fps": None})
        time.sleep(poll_s)
        if fh and current and not current.exists():
            fh.close()
            fh, current = None, None


def main_tail() -> int:
    try:
        tail()
    except KeyboardInterrupt:
        pass
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main_tail())
